### ISSUE TITLE
TrackOpens and TrackClicks overriding mandril default options

### ISSUE THREAD

**Issue by epelc** [mattbaird/gochimp#33]
If you don't set `TrackOpens` or `TrackClicks` they are set to false and overriding mandrills default sending options.

Ie this happens even if you don't set them to false. Perhaps a NewMessage() func could fix this or adding functions to set them since they really have 3 values true, false, and none(default to mandrill settings).

**Comment by mattbaird** [comment]
fixed.

**Comment by epelc** [comment]
@mattbaird Thanks!
